### PR TITLE
Added mftf selenium support

### PR DESCRIPTION
**Pull request by apedicdev**
please amend

### CODE REVIEW

**Comment by cmtickle** [comment]
I think upgrading Redis to v7 is a step too far, unfortunately not everyone will be on the latest Redis version.
See Magento requirements for v2.4 https://experienceleague.adobe.com/docs/commerce-operations/installation-guide/system-requirements.html
Also, adding an alias in this way would mean it needs adding for any/all hostnames. I wonder if there's a programmatic to add the alias when you start the containers with the project script?

**Comment by apedicdev** [comment]
ok, I think given magento 2.4.4 is at least still supported we can upgrade
to redis 6.2

Antonio Pedicini
mobile (UK): +44 7990430459

**Comment by cmtickle** [comment]
@apedicdev I'll wait for the work you'r doing on dynamic network aliases to be completed before I merge this. Thanks.

**Comment by apedicdev** [comment]
@cmtickle it was added in the last commit, please have a look here https://github.com/cmtickle/docker-stack/pull/10/commits/26e799a0987f89fc064e6a8db8285e54305ca13a

**Comment by cmtickle** [comment]
Apologies @apedicdev , I missed that. Please can you remove the hard-coded alias https://github.com/cmtickle/docker-stack/pull/10/files#diff-75ad18c5bbdec38f0d770b9160da81f28cd04ec504442972012a55d3c1d3d780R65

**Comment by apedicdev** [comment]
no problen @cmtickle. Removed it, thanks I forgot

**Comment by cmtickle** [comment]
@apedicdev using basename to work out which project is running does not work when files are not synchronised and when you run the script from somewhere other than the project folder.. lets discuss

**Comment by apedicdev** [comment]
should not return the install directory as in `docker-stack` where it has been cloned the stack itself?

**Comment by cmtickle** [comment]
All great now. Thanks again!

**Review by cmtickle — APPROVED** [review]

**Pull request merged**
